language: python
python:
  - "2.7"

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27

before_install:
  - pip install --upgrade setuptools pip wheel

# command to install dependencies
install:
  - pip install -r requirements-test.txt

# command to run tests
script:
  - tox
