language: python

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34

before_install:
  - pip install --upgrade setuptools pip wheel

# command to install dependencies
install:
  - pip install -r requirements-build.txt

# command to run tests
script:
  - tox
